language: php
php:
    - '7.1'
      #- '5.6'
before_script:
    - phpunit --version
    - touch enabletests
    - rm composer.lock
    - rm -r third_party
    - composer update
    - composer install
    - chmod -R 777 tmp
    - chmod -R 777 upload

    # Install Apache
    # Code fetched from https://docs.travis-ci.com/user/languages/php/#Apache-%2B-PHP
    - sudo apt-get update > /dev/null
    - sudo apt-get -y --force-yes install apache2 libapache2-mod-fastcgi nodejs
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
    - sudo chown -R travis:travis /var/lib/apache2/fastcgi
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    - sudo cp -f tests/travis/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    - sudo service apache2 restart

    # Phantomjs setup.
    - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    - tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
    - ./phantomjs-2.1.1-linux-x86_64/bin/phantomjs  --webdriver=127.0.0.1:4444 &

script:
    - phpunit
