# This workflow will prepare and test the frontend

name: LimeSurvey - Frontend - CI pipeline

# Triggers the workflow on push or pull request events on all branches
on:
  pull_request:
  push:
    branches:
      - '*'
      - '**'
      - 'dev/**'
      - 'bug/**'
      - 'feature/**'
      - 'zoho/**'

permissions:
  contents: read

jobs:
  job_build_packages:
    runs-on: ubuntu-22.04 # ubuntu runner hosted by Github
    concurrency: 
      group: ${{ github.ref_name }}-frontend # Groups by branch and job name 
      cancel-in-progress: true # Cancel in-progress jobs if a new job is triggered     
    strategy:
      matrix:
        # Specify what version of nodejs you want to test
        nodeJS-versions: ['20.19.0']
    name: Build Frontend Packages
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup nodeJS
        uses: actions/setup-node@v4
        with:
            node-version: 20

      - name: Run composer
        run: |
          composer install -vvv

      - name: Run yarn
        run: |
          yarn install

      - name: Install adminbasics
        run: |
          cd ${{ github.workspace }}
          yarn --cwd ./assets/packages/adminbasics 
      
      - name: Build adminbasics
        run: |
          cd ${{ github.workspace }}
          yarn --cwd ./assets/packages/adminbasics build
        
     # - name: Install adminsidepanel
     #   run: |
     #     cd ${{ github.workspace }}
      #    yarn --cwd ./assets/packages/adminsidepanel
          
     # TODO: Enable this step, when its possible to build adminsidepanel again 
     # - name: Build adminsidepanel
      #  run: |
       #   cd ${{ github.workspace }}
        #  yarn --cwd ./assets/packages/adminsidepanel build
    
  job_run_tests:
    needs: [job_build_packages]
    runs-on: ubuntu-22.04 # ubuntu runner hosted by Github
    strategy:
      matrix:
        # Specify what version of nodejs you want to test
        nodeJS-versions: ['20.19.0']
    name: Run Frontend Tests
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Setup nodeJS
        uses: actions/setup-node@v4
        with:
            node-version: 20

      - name: Install adminbasics
        run: |
          cd ${{ github.workspace }}
          yarn --cwd ./assets/packages/adminbasics

    #  - name: Install adminsidepanel
    #    run: |
     #     cd ${{ github.workspace }}
     #     yarn --cwd ./assets/packages/adminsidepanel
      
      - name: Run Tests
        run: |
          cd ${{ github.workspace }}
          yarn --cwd ./assets/packages/adminbasics run test
        #  yarn --cwd ./assets/packages/adminsidepanel run test
  
    
